// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/ActiManage-core-api/biz/adaptor"
	"github.com/xh-polaris/ActiManage-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/ActiManage-core-api/biz/application/dto/core_api"
)

// MerchantListActivities .
// @router /merchant/activity/list [POST]
func MerchantListActivities(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListActivitiesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantListActivities(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantCreateActivity .
// @router /merchant/activity/create [POST]
func MerchantCreateActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantCreateActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantCreateActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantDeleteActivity .
// @router /merchant/activity/delete [POST]
func MerchantDeleteActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantDeleteActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantDeleteActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantTopActivity .
// @router /merchant/activity/top [POST]
func MerchantTopActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantTopActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantTopActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantLogin .
// @router /merchant/login [POST]
func MerchantLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantLogin(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantGetSetting .
// @router /merchant/setting/get [GET]
func MerchantGetSetting(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantGetSettingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantGetSetting(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantUpdateSetting .
// @router /merchant/setting/update [POST]
func MerchantUpdateSetting(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantUpdateSettingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantUpdateSetting(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantListBookRecords .
// @router /merchant/book/list [POST]
func MerchantListBookRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListBookRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantListBookRecords(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantUpdateInfo .
// @router /merchant/info/update [POST]
func MerchantUpdateInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantUpdateInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantUpdateInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantGetInfo .
// @router /merchant/info/get [GET]
func MerchantGetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantGetInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantGetInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantSetPassword .
// @router /merchant/password/set [POST]
func MerchantSetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantSetPasswordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantSetPassword(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetMerchantInfoByUri .
// @router /merchant/info/uri [POST]
func GetMerchantInfoByUri(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetMerchantInfoByUriReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.GetMerchantInfoByUri(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetAd .
// @router /merchant/ad/get [POST]
func GetAd(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetAdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.GetAd(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SetAd .
// @router /merchant/ad/update [POST]
func SetAd(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SetAdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.SetAd(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantUpdateActivity .
// @router /merchant/activity/update [POST]
func MerchantUpdateActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantUpdateActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantUpdateActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantGetActivity .
// @router /merchant/activity/get [POST]
func MerchantGetActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantGetActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.MerchantService.MerchantGetActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// MerchantListUsers .
// @router /merchant/user/list [POST]
func MerchantListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListUsersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.MerchantListUsersResp)

	c.JSON(consts.StatusOK, resp)
}

// MerchantListReservers .
// @router /merchant/reserver/list [POST]
func MerchantListReservers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListReserversReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.MerchantListReserversResp)

	c.JSON(consts.StatusOK, resp)
}

// MerchantListViews .
// @router /merchant/view/list [POST]
func MerchantListViews(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListViewsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.MerchantListViewsResp)

	c.JSON(consts.StatusOK, resp)
}

// MerchantListFavorites .
// @router /merchant/favorite/list [POST]
func MerchantListFavorites(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListFavoritesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.MerchantListFavoritesResp)

	c.JSON(consts.StatusOK, resp)
}

// MerchantListAllBookRecords .
// @router /merchant/book/list_all [POST]
func MerchantListAllBookRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.MerchantListAllBookRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.MerchantListAllBookRecordsResp)

	c.JSON(consts.StatusOK, resp)
}
