// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/ActiManage-core-api/biz/adaptor"
	"github.com/xh-polaris/ActiManage-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/ActiManage-core-api/biz/application/dto/core_api"
)

// StsApplySignedUrl .
// @router /sts/cos/apply [POST]
func StsApplySignedUrl(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.StsApplySignedUrlReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.StsService.StsApplySignedUrl(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// StsAIModify .
// @router /sts/ai/modify [POST]
func StsAIModify(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.StsAIModifyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.StsService.StsAIModify(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
