// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/ActiManage-core-api/biz/adaptor"
	"github.com/xh-polaris/ActiManage-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/ActiManage-core-api/biz/application/dto/core_api"
)

// SystemLogin .
// @router /system/login [POST]
func SystemLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemLogin(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemListMerchant .
// @router /system/merchant/list [POST]
func SystemListMerchant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemListMerchantsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemListMerchant(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemGetMerchant .
// @router /system/merchant/get [POST]
func SystemGetMerchant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemGetMerchantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemGetMerchant(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemCreateMerchant .
// @router /system/merchant/create [POST]
func SystemCreateMerchant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemCreateMerchantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemCreateMerchant(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemUpdateMerchant .
// @router /system/merchant/update [POST]
func SystemUpdateMerchant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemUpdateMerchantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemUpdateMerchant(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemGetDashboard .
// @router /system/dashboard/one [POST]
func SystemGetDashboard(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemGetDashboardReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemGetDashboard(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SystemGetOverallDashboard .
// @router /system/dashboard/overall [GET]
func SystemGetOverallDashboard(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SystemGetOverallDashboardReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.SystemService.SystemGetOverallDashboard(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}
