// Code generated by hertz generator.

package core_api

import (
	"context"
	"github.com/xh-polaris/ActiManage-core-api/biz/adaptor"
	"github.com/xh-polaris/ActiManage-core-api/provider"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	core_api "github.com/xh-polaris/ActiManage-core-api/biz/application/dto/core_api"
)

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.Login(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// SignUp .
// @router /user/signup [POST]
func SignUp(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.SignUpReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.SignUp(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetSetting .
// @router /user/settings/get [POST]
func GetSetting(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetSettingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.GetSetting(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListActivities .
// @router /user/activity/list [POST]
func ListActivities(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListActivitiesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.ListActivities(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetActivity .
// @router /user/activity/get [POST]
func GetActivity(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetActivityReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.GetActivity(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// DoFavorite .
// @router /user/favorite/do [POST]
func DoFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DoFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.DoFavorite(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CancelFavorite .
// @router /user/favorite/cancel [POST]
func CancelFavorite(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CancelFavoriteReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.CancelFavorite(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CreateBooking .
// @router /user/book/create [POST]
func CreateBooking(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateBookingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.CreateBooking(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CancelBookRecord .
// @router /user/book/cancel [POST]
func CancelBookRecord(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CancelBookRecordReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.CancelBookRecord(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListActivitiesByBookRecords .
// @router /user/book/list/activity [POST]
func ListActivitiesByBookRecords(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListActivitiesByBookRecordsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.ListActivitiesByBookRecords(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// ListReservers .
// @router /user/reserver/list [POST]
func ListReservers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.ListReserversReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.ListReservers(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// CreateReserver .
// @router /user/reserver/create [POST]
func CreateReserver(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.CreateReserverReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.CreateReserver(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// DeleteReserver .
// @router /user/reserver/delete [POST]
func DeleteReserver(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.DeleteReserverReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.DeleteReserver(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetUserInfo .
// @router /user/info/get [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.GetUserInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// UpdateUserInfo .
// @router /user/info/update [POST]
func UpdateUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateUserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.UpdateUserInfo(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// UpdateNotice .
// @router /user/info/notice [POST]
func UpdateNotice(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.UpdateNoticeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	p := provider.Get()
	resp, err := p.UserService.UpdateNotice(ctx, &req)
	adaptor.PostProcess(ctx, c, &req, resp, err)
}

// GetMerchantInfo .
// @router /user/merchant/info/get [POST]
func GetMerchantInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core_api.GetMerchantInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core_api.GetMerchantInfoResp)

	c.JSON(consts.StatusOK, resp)
}
