// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/ActiManage-core-api/biz/application/service"
	"github.com/xh-polaris/ActiManage-core-api/biz/infrastructure/config"
	"github.com/xh-polaris/ActiManage-core-api/biz/infrastructure/rpc/system"
	"github.com/xh-polaris/ActiManage-core-api/biz/infrastructure/rpc/user"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	client := system.NewActiManageSystem(configConfig)
	actiManageSystem := &system.ActiManageSystem{
		Client: client,
	}
	userserviceClient := user.NewActiManageUser(configConfig)
	actiManageUser := &user.ActiManageUser{
		Client: userserviceClient,
	}
	merchantService := service.MerchantService{
		SystemRpc: actiManageSystem,
		UserRpc:   actiManageUser,
		Config:    configConfig,
	}
	stsService := service.StsService{
		SystemRpc: actiManageSystem,
		UserRpc:   actiManageUser,
	}
	systemService := service.SystemService{
		SystemRpc: actiManageSystem,
		UserRpc:   actiManageUser,
		Config:    configConfig,
	}
	userService := service.UserService{
		UserRpc:   actiManageUser,
		SystemRpc: actiManageSystem,
		Config:    configConfig,
	}
	providerProvider := &Provider{
		Config:          configConfig,
		MerchantService: merchantService,
		StsService:      stsService,
		SystemService:   systemService,
		UserService:     userService,
	}
	return providerProvider, nil
}
