// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/ActiManage-core-api/biz/application/service"
	"github.com/xh-polaris/ActiManage-core-api/biz/infrastructure/config"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	merchantService := service.MerchantService{}
	stsService := service.StsService{}
	systemService := service.SystemService{}
	userService := service.UserService{}
	providerProvider := &Provider{
		Config:          configConfig,
		MerchantService: merchantService,
		StsService:      stsService,
		SystemService:   systemService,
		UserService:     userService,
	}
	return providerProvider, nil
}
