// Code generated by hertz generator. DO NOT EDIT.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	core_api "github.com/xh-polaris/ActiManage-core-api/biz/adaptor/controller/core_api"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_merchant := root.Group("/merchant", _merchantMw()...)
		_merchant.POST("/login", append(_merchantloginMw(), core_api.MerchantLogin)...)
		{
			_activity := _merchant.Group("/activity", _activityMw()...)
			_activity.POST("/create", append(_merchantcreateactivityMw(), core_api.MerchantCreateActivity)...)
			_activity.POST("/delete", append(_merchantdeleteactivityMw(), core_api.MerchantDeleteActivity)...)
			_activity.POST("/list", append(_merchantlistactivitiesMw(), core_api.MerchantListActivities)...)
			_activity.POST("/top", append(_merchanttopactivityMw(), core_api.MerchantTopActivity)...)
		}
		{
			_ad := _merchant.Group("/ad", _adMw()...)
			_ad.POST("/get", append(_getadMw(), core_api.GetAd)...)
			_ad.POST("/update", append(_setadMw(), core_api.SetAd)...)
		}
		{
			_book := _merchant.Group("/book", _bookMw()...)
			_book.POST("/list", append(_merchantlistbookrecordsMw(), core_api.MerchantListBookRecords)...)
		}
		{
			_info := _merchant.Group("/info", _infoMw()...)
			_info.GET("/get", append(_merchantgetinfoMw(), core_api.MerchantGetInfo)...)
			_info.POST("/update", append(_merchantupdateinfoMw(), core_api.MerchantUpdateInfo)...)
			_info.POST("/uri", append(_getmerchantinfobyuriMw(), core_api.GetMerchantInfoByUri)...)
		}
		{
			_password := _merchant.Group("/password", _passwordMw()...)
			_password.POST("/set", append(_merchantsetpasswordMw(), core_api.MerchantSetPassword)...)
		}
		{
			_setting := _merchant.Group("/setting", _settingMw()...)
			_setting.GET("/get", append(_merchantgetsettingMw(), core_api.MerchantGetSetting)...)
			_setting.POST("/update", append(_merchantupdatesettingMw(), core_api.MerchantUpdateSetting)...)
		}
	}
	{
		_sts := root.Group("/sts", _stsMw()...)
		_sts.POST("/view", append(_stsviewMw(), core_api.StsView)...)
		{
			_ai := _sts.Group("/ai", _aiMw()...)
			_ai.POST("/modify", append(_stsaimodifyMw(), core_api.StsAIModify)...)
		}
		{
			_cos := _sts.Group("/cos", _cosMw()...)
			_cos.POST("/apply", append(_stsapplysignedurlMw(), core_api.StsApplySignedUrl)...)
		}
		{
			_verify := _sts.Group("/verify", _verifyMw()...)
			_verify.POST("/send", append(_stssendverifycodeMw(), core_api.StsSendVerifyCode)...)
		}
	}
	{
		_system := root.Group("/system", _systemMw()...)
		_system.POST("/login", append(_systemloginMw(), core_api.SystemLogin)...)
		{
			_dashboard := _system.Group("/dashboard", _dashboardMw()...)
			_dashboard.POST("/one", append(_systemgetdashboardMw(), core_api.SystemGetDashboard)...)
			_dashboard.POST("/overall", append(_systemgetoveralldashboardMw(), core_api.SystemGetOverallDashboard)...)
		}
		{
			_merchant0 := _system.Group("/merchant", _merchant0Mw()...)
			_merchant0.POST("/create", append(_systemcreatemerchantMw(), core_api.SystemCreateMerchant)...)
			_merchant0.POST("/get", append(_systemgetmerchantMw(), core_api.SystemGetMerchant)...)
			_merchant0.POST("/list", append(_systemlistmerchantMw(), core_api.SystemListMerchant)...)
			_merchant0.POST("/update", append(_systemupdatemerchantMw(), core_api.SystemUpdateMerchant)...)
		}
	}
	{
		_user := root.Group("/user", _userMw()...)
		_user.POST("/login", append(_loginMw(), core_api.Login)...)
		_user.POST("/signup", append(_signupMw(), core_api.SignUp)...)
		{
			_activity0 := _user.Group("/activity", _activity0Mw()...)
			_activity0.POST("/get", append(_getactivityMw(), core_api.GetActivity)...)
			_activity0.POST("/list", append(_listactivitiesMw(), core_api.ListActivities)...)
		}
		{
			_book0 := _user.Group("/book", _book0Mw()...)
			_book0.POST("/cancel", append(_cancelbookrecordMw(), core_api.CancelBookRecord)...)
			_book0.POST("/create", append(_createbookingMw(), core_api.CreateBooking)...)
			{
				_list := _book0.Group("/list", _listMw()...)
				_list.POST("/activity", append(_listactivitiesbybookrecordsMw(), core_api.ListActivitiesByBookRecords)...)
			}
		}
		{
			_favorite := _user.Group("/favorite", _favoriteMw()...)
			_favorite.POST("/cancel", append(_cancelfavoriteMw(), core_api.CancelFavorite)...)
			_favorite.POST("/do", append(_dofavoriteMw(), core_api.DoFavorite)...)
		}
		{
			_info0 := _user.Group("/info", _info0Mw()...)
			_info0.GET("/get", append(_getuserinfoMw(), core_api.GetUserInfo)...)
			_info0.POST("/notice", append(_updatenoticeMw(), core_api.UpdateNotice)...)
			_info0.POST("/update", append(_updateuserinfoMw(), core_api.UpdateUserInfo)...)
		}
		{
			_merchant1 := _user.Group("/merchant", _merchant1Mw()...)
			{
				_info1 := _merchant1.Group("/info", _info1Mw()...)
				_info1.POST("/get", append(_getmerchantinfoMw(), core_api.GetMerchantInfo)...)
			}
		}
		{
			_reserver := _user.Group("/reserver", _reserverMw()...)
			_reserver.POST("/create", append(_createreserverMw(), core_api.CreateReserver)...)
			_reserver.POST("/delete", append(_deletereserverMw(), core_api.DeleteReserver)...)
			_reserver.POST("/list", append(_listreserversMw(), core_api.ListReservers)...)
			_reserver.POST("/update", append(_updatereserverMw(), core_api.UpdateReserver)...)
		}
		{
			_settings := _user.Group("/settings", _settingsMw()...)
			_settings.POST("/get", append(_getsettingMw(), core_api.GetSetting)...)
		}
		{
			_view := _user.Group("/view", _viewMw()...)
			{
				_list0 := _view.Group("/list", _list0Mw()...)
				_list0.POST("/activity", append(_listactivitiesbyviewMw(), core_api.ListActivitiesByView)...)
			}
		}
	}
}
