// Code generated by hertz generator.

package core_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantcreateactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantdeleteactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantlistactivitiesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchanttopactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantlistbookrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantupdateinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantsetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetsettingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantupdatesettingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsaimodifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsapplysignedurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemgetdashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemgetoveralldashboardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchant0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemcreatemerchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemgetmerchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemlistmerchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemupdatemerchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signupMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _activity0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getactivityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listactivitiesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _book0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelbookrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createbookingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listactivitiesbybookrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelfavoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dofavoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _info0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenoticeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createreserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletereserverMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreserversMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsettingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _verifyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stssendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stsviewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmerchantinfobyuriMw() []app.HandlerFunc {
	// your code...
	return nil
}
